### ISSUE TITLE
Depends on NDMF instead of MA

### ISSUE THREAD

**Issue by anatawa12** [Narazaka/FloorAdjuster#2]
I think this tool doesn't need to depends on MA

**Comment by Narazaka** [comment]
`InPhase(BuildPhase.Transforming).AfterPlugin("nadena.dev.modular-avatar")`である必要があるのでMAかなとしていましたが、NDMFでもいいんですかね

**Comment by anatawa12** [comment]
文字列指定のAfterPluginは前後方向の定義だけでインストールされてることを要求しないので、NDMFだけでいいはずです。

**Comment by anatawa12** [comment]
一応一回はpullreq作成時に動作確認はした記憶があります

**Comment by Narazaka** [comment]
プルリク採用しなくて恐縮ですがたぶん直しました（MA1.8.0時点での依存広さに合わせています）

**Comment by anatawa12** [comment]
よさそうですね
